# services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]


services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: ["@mailer", %locale%, "50"]

    oc_platform.advert_purger:
         class: OC\PlatformBundle\Advert_purger\OCPurger
         arguments: ["@doctrine"]