
oc_core_home:
        path:     /
        defaults: { _controller: OCCoreBundle:Core:home }

oc_core_contact:
        path:     /contact
        defaults: { _controller: OCCoreBundle:Core:contact }

oc_core_platform:
        path:     /Platform
        defaults: { _controller: OCCoreBundle:Core:index }
